### ISSUE TITLE
Expiration time?

### ISSUE THREAD

**Issue by rocker8942** [Sam-Martin/Ephemera#11]
Hi Sam, 

Does this have an expiration after like 24 hours?  Or is it available forever unless the link is not clicked?

Regards
Joe

**Comment by Sam-Martin** [comment]
If you use serverless to deploy it you'll inherit the default bucket lifecycle policy of 14 day deletion (found in the [config.yml](https://github.com/Sam-Martin/Ephemera/blob/master/serverless-ephemera/config.yml)).
