### ISSUE TITLE
Nodejs 4.3 is no longer supported

### ISSUE THREAD

**Issue by babyhuey** [Sam-Martin/Ephemera#17]
When I try to deploy, I get the following error:

> An error occurred: EphemeraPopulateStaticSiteConfigLambdaFunction - The runtime parameter of nodejs4.3 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: f5c800b6-2a31-11e9-9b39-db0fcdad817a).

Pull request here: https://github.com/Sam-Martin/Ephemera/pull/16

**Comment by markwragg** [comment]
Fixed by #18
